config/routes.rb
YoumixrOR::Application.routes.draw do

  root :to => "static_pages#home"

  get "home", to: "static_pages#home"
  get "help", to:  "static_pages#help"
  get "run", to: "static_pages#run"

  get "log_out" => "sessions#destroy", as: :log_out
  get "session", to: "static_pages#index"
  resource :sessions
  
  resources :histories, :only => [:delete, :show]

  resources :users, constraints: {id: /\d+/}, except: [:index] do 
    resources :histories, only: [:index]
    member do
      get 'playlists', to: 'users#playlists', constraints: {id: /\d+/}
    end
  end

  resources :playlists, constraints: {id: /\d+/} do
    member do
      get 'select'
    end

    collection do
      get 'addSong/:sid', to: 'playlist_entries#create', constraints: {sid: /yt:(\w|-)+|sc:\d+|vi:\d+/}
      get 'removeSong/:playlist_entry_id', to: 'playlist_entries#destroy', constraints: {playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id/:next_playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/, next_playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/}
    end

    resources :playlist_entries, only: [:destroy, :create], constraints: {id: /\d+/} do
      post 'add', to: :create
      delete 'remove', to: :destroy 
    end
  end
  
  get '/songs/soundcloudTemplate', to: "songs#soundcloudTemplate"

  resources :songs, constraints: {id: /yt:(\w|-)+|sc:\d+|vi:\d+/} do  
    member do 
      get 'play'
    end
    collection do
      get "search"
    end
  end

  resources :vimeo, controller: :vimeo_wrappers, only: [:index]

end

app/models/song.rb
class Song < ActiveRecord::Base

  has_many :playlist_entries, :dependent => :destroy
  has_many :playlists, through: :playlist_entries

  has_many :histories, :dependent => :destroy
  has_many :users, through: :histories

  def self.findOrCreate(sid, title, artist=nil)
  		if !title.nil?
			@song = Song.find_or_create_by_sid(sid) do |t|
				t.title = title.strip
				if !artist.nil?
					t.artist = artist.strip
				end				
				t.play_count = 0
			end
			@song.play_count += 1
			@song.save
			@song
		else
			raise "No song title!" 
		end
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  # GET /songs
  # GET /songs.json
  def index
    if params[:source_filter].nil?
      @songs = Song.all
      
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @songs }
      end      
    end
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
    plattform = params[:id].split(':')
    if plattform[0] == "yt"     
      @yt_video = YM_Youtube.client.video_by(plattform[1])
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /songs/new
  # GET /songs/new.json
  def new
    @song = Song.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @song }
    end
  end

  # GET /songs/1/edit
  def edit
    @song = Song.find(params[:id])
  end

  # POST /songs
  # POST /songs.json
  def create
    @song = Song.create(sid: params[:id], artist: params[:artist], title: params[:title])

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render json: @song, status: :created, location: @song }
      else
        format.html { render action: "new" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /songs/1
  # PUT /songs/1.json
  def update
    @song = Song.find(params[:id])

    respond_to do |format|
      if @song.update_attributes(params[:song])
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song = Song.find(params[:id])
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url }
      format.json { head :no_content }
    end
  end

  def play

    @song = Song.findOrCreate(params[:id], params[:title], params[:artist]) 

    if logged_in?
      @history_entry = History.create(user_id: current_user.id, song_id: @song.id, played_at: Time.now)
      if !@history_entry.save
        flash[:notice] = "Error while creating a history entry for the current song."
      end
    end

    plattform = params[:id].split(':')
    if plattform == "yt"
      @song = YM_Plattform.create(params[:id])

      respond_to do |format|
        format.js {render :template => @song.get_player }
        format.html { render :template => @song.get_player }
      end
    end

    render :nothing => true

  end
  
  def search
    # Youtube Search
    if params[:source_filter].nil? 
      render :nothing => true
    else
      if params[:source_filter].include?("yt")
          
          @yt_videos = YM_Youtube.client.videos_by(:query => params[:song_search], :page => 1, :per_page => 10).videos
          @search_route = "_youtube_search_results"
      end
      respond_to do |format|
        format.html {render @search_route, :layout => false}
        format.js
      end
    end
  end

  def soundcloudTemplate
    respond_to do |format|
      format.html {render "_soundcloud_search_results", :layout => false}
      format.js 
    end
  end

end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/_soundcloud_search_results.html.erb
<li class="clearfix media search-thumbnail">
    <a class="pull-left play-song" href="#">
      <img class="media-object" src="#" alt="Default">
    </a>
    <div class="media-body">
      <p class="pull-right">         
         <a class="close" data-remote="true">&times;</a>        
         <span class="btn btn-small add-song"><i class='icon-plus-sign'></i></span>      
         <span class="btn btn-small play-song"><i class='icon-play'></i></span>       
      </p>
      <h4 class="media-heading truncate songtitle"></h4>
      <span class="truncate artistname"></span>

    </div>
</li>

app/views/songs/_youtube_search_results.html.erb
<% @yt_videos.each do |video|
     title = video.title.split('-', 2)
     videotitle = (title.length == 2)? {:title => title[1], :author => title[0]} : {:title => title[0], :author => ""}

     playlist = (!session[:playlist].nil?)? session[:playlist].id : 0
%>
  <li class="clearfix" data-song-id="yt:<%= video.unique_id %>">
    <div class="search-thumbnail pull-left">
      <%= image_tag(video.thumbnails[0].url, :size=>"60x60") %>
    </div>
    <div>
        <p class="pull-right">
         <%= link_to raw("&times;"), "playlists/"+playlist.to_s+"/remove/yt:" + video.unique_id, :remote=>true, :class=>"close" %>          
          <span title="add to playlist..." class="btn btn-small add-song"><i class='icon-plus-sign'></i></span>
          <span title="start playing..." class="btn btn-small play-song"><i class='icon-play'></i></span>
        </p>
      <p class="truncate artistname"><%= videotitle[:author]%></p>
      <p class="truncate songtitle">
        <%= link_to videotitle[:title], song_path("yt:" + video.unique_id), :remote => true %>
      </p>
    </div>
  </li>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<div class="container">
  <div class="row">
    <%= render "searchform" %>
    <%= render "playlists/small_list" %>
    <div class="col-md-8">
      <h1>Search Results</h1>        	
      <ul class="search-result-list unstyled connectedSortable"></ul>
    </div>      
  </div><!--/row-->
</div><!--/container-->

app/views/songs/index.js.erb
$("#mainframe").html("<%= escape_javascript(render :template => 'songs/index', :formats => [:html]) %>");

app/views/songs/new.html.erb
<h1>New song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/sc_play.js.erb
SC.initialize({
  client_id: '<%= SoundcloudConfig.client_id %>'
});

var track_url = '<%= @song.song_url %>';
SC.oEmbed(track_url, { show_artwork: false, auto_play: false,  maxwidth: 350 }, function(oEmbed) {
  $(".sc-player")
        .parent().fadeTo( 1, 0, function() { $(this).removeAttr("style") } );

  $("#<%= @song.id %> div.pull-right")
	.css({ opacity: 1})
	.append(oEmbed['html']);
  $("#<%= @song.id %> iframe")
	.addClass("sc-player");
  $("#<%= @song.id %> .sc-player")
	.animate({width: "350px"}, 1500);
 
});

app/views/songs/search.js.erb
$(".search-result-list").html("<%= escape_javascript(render @search_route , :formats => [:html]) %>");

app/views/songs/show.html.erb
<p>
  <b>Title:</b>
  <%= debug @yt_video 
      if !@yt_video.nil? 
	@yt_video.title 
      elsif !@sc_song.nil?
        @sc_song[:id]
      else
	puts "no title"
      end
  %>
</p>

<p>
  <%= if !@yt_video.nil? 
	@yt_video.embed_html5.html_safe 
      elsif !@sc_song.nil?
	debug @sc_song
        @sc_song[:access_token]
      else
	puts "no title"
      end
  %>
  </p>

<%= link_to 'Back', songs_path %>

app/views/songs/show.js.erb
$("#mainframe").html("<%= escape_javascript(render :template =>'songs/show.html.erb')%>");

app/views/songs/yt_play.js.erb
/*$(".yt-player")
        .parent().fadeTo( 1, 0, function() { $(this).removeAttr("style") } );

$("#<%= @song.id %> div.pull-right")
	.css({ opacity: 1})
	.append("<%= escape_javascript(raw(@song.player))%>");
$("#<%= @song.id %> .yt-player")
	.animate({width: "350px"}, 1500);
*/

$("#hidden-player").append("<%= escape_javascript(raw(@song.player))%>");