config/routes.rb
YoumixrOR::Application.routes.draw do

  root :to => "static_pages#home"

  get "home", to: "static_pages#home"
  get "help", to:  "static_pages#help"
  get "run", to: "static_pages#run"

  get "log_out" => "sessions#destroy", as: :log_out
  get "session", to: "static_pages#index"
  resource :sessions
  
  resources :histories, :only => [:delete, :show]

  resources :users, constraints: {id: /\d+/}, except: [:index] do 
    resources :histories, only: [:index]
    member do
      get 'playlists', to: 'users#playlists', constraints: {id: /\d+/}
    end
  end

  resources :playlists, constraints: {id: /\d+/} do
    member do
      get 'select'
    end

    collection do
      get 'addSong/:sid', to: 'playlist_entries#create', constraints: {sid: /yt:(\w|-)+|sc:\d+|vi:\d+/}
      get 'removeSong/:playlist_entry_id', to: 'playlist_entries#destroy', constraints: {playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id/:next_playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/, next_playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/}
    end

    resources :playlist_entries, only: [:destroy, :create], constraints: {id: /\d+/} do
      post 'add', to: :create
      delete 'remove', to: :destroy 
    end
  end
  
  get '/songs/soundcloudTemplate', to: "songs#soundcloudTemplate"

  resources :songs, constraints: {id: /yt:(\w|-)+|sc:\d+|vi:\d+/} do  
    member do 
      get 'play'
    end
    collection do
      get "search"
    end
  end

  resources :vimeo, controller: :vimeo_wrappers, only: [:index]

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :creator, class_name: "User"

  has_many :playlist_entries, -> { order("position ASC") }, dependent: :destroy
  has_many :songs, through: :playlist_entries

  validates :title, presence: :true
  validates :creator, presence: :true

  self.per_page = 5

  scope :published, -> { where(published: :t) }

end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_filter :signed_in_user, :only => [:new, :edit, :update, :create, :destroy]
  before_filter :set_playlist, :only => [:show, :edit, :update, :destroy, :select]

  rescue_from ActiveRecord::RecordNotFound do
    flash[:notice] = 'The Playlist you tried to access does not exist'
    redirect_to run_path   
  end

  # GET /playlists
  # GET /playlists.json
  def index
    if (@playlists = Playlist.published).nil?
      respond_to do |format|
        format.html {redirect_to run_path }
      end
    else
      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @playlists }
      end
    end
  end

  # GET /playlists/1
  # GET /playlists/1.json
  def show
    @playlist_entries = @playlist.playlist_entries.page(params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/new
  # GET /playlists/new.json
  def new
    @playlist = Playlist.new(creator: current_user)

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @playlist }
    end
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists
  # POST /playlists.json
  def create
    @playlist = Playlist.create(params[:playlist])
    @playlist.creator = current_user

    respond_to do |format|
      if @playlist.save
        session[:playlist] = @playlist.id

        format.html { redirect_to @playlist, notice: 'Playlist was successfully created.' }
        format.json { render json: @playlist, status: :created, location: @playlist }
      else
        puts @playlist.to_yaml
        format.html { render action: "new" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /playlists/1
  # PUT /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update_attributes(params[:playlist])
        format.html { redirect_to @playlist, notice: 'Playlist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1
  # DELETE /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url }
      format.json { head :no_content }
    end
  end

  #GET /playlists/:id/select
  def select
      if !@playlist.published
        if !logged_in? or (logged_in? and @playlist.creator != current_user)
          flash[:notice] = "The creator of the choosen playlist, marked it as private."
          session[:playlist] = nil
        end        
      end

    session[:playlist] = @playlist.id
    redirect_to run_path 
  end

  private 
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
  def choosed_playlist
    return (logged_in? and !session[:playlist].nil?)
  end

  def choosed_own_playlist
    return (choosed_playlist and Playlist.where(id: session[:playlist], creator: current_user).exists?)
  end
end

app/views/playlists/_form.html.erb
<%= form_for @playlist, html:{class: "form-horizontal", role:"form"} do |f| %>
  <% if @playlist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
      <% @playlist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => "form-control", :rows => 3 %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :creator, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <p class="form-control-static"><%= @playlist.creator.name %></p>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :published, :class => "col-lg-2 control-label" %>
    <div class="col-lg-10">
      <%= f.check_box :published %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => "btn btn-default" %>
      <%= link_to 'Show', @playlist, :class => "btn btn-link" %>
      <% if !@playlist.id.nil? %>
        <%= link_to 'Play', select_playlist_path(@playlist), :class => "btn btn-link" %>
      <% end %>
      <%= link_to 'Back', user_path(current_user), :class => "btn btn-link" %>
    </div>
  </div>
<% end %>

app/views/playlists/_list_with_owner.html.erb
<table class="table table-condensed">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>User</th>
    <th>Published</th>
    <th></th>
  </tr>
<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.title %></td>
    <td><%= playlist.description %></td>
    <td><%= playlist.creator.name %></td>
    <td>
      <%= check_box_tag 'published', '', playlist.published, :disabled => true %>
    </td>
    <td><%= link_to 'Show', playlist, :class => "btn btn-link" %>
        <%= link_to 'Play', select_playlist_path(playlist), :class => "btn btn-link" %>
        <% if logged_in? %>
          <% if current_user == playlist.creator %>
            <%= link_to 'Edit', edit_playlist_path(playlist), :class => "btn btn-link" %>
          <% end %>
        
          <%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/playlists/_list_without_owner.html.erb
<table class="table table-condensed">
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Published</th>
    <th></th>
  </tr>
<% @playlists.each do |playlist| %>
  <tr>
    <td><%= playlist.title %></td>
    <td><%= playlist.description %></td>
    <td>
      <%= check_box_tag 'published', '', playlist.published, :disabled => true %>
    </td>
    <td><%= link_to 'Show', playlist, :class => "btn btn-link" %>
        <%= link_to 'Play', select_playlist_path(playlist), :class => "btn btn-link" %>
        <% if logged_in? %>
          <% if current_user == playlist.creator %>
            <%= link_to 'Edit', edit_playlist_path(playlist), :class => "btn btn-link" %>
          <% end %>
        
          <%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

app/views/playlists/_small_list.html.erb
<div class="col-md-4 playlist">
  <h3>Playlist
   	<% if !@playlist.nil? %>
  		 	<span class="playlist-title">
         - <%= link_to @playlist.title, playlist_path(@playlist), class: "btn-link" %>
        </span>
  	<% end %>
  </h3>
   
	<% if logged_in? %>  
	  <%= form_tag(playlists_path(format: :json), remote: true, :class=>"new_playlist") do |f| %>
	  	<button class="btn btn-inverse btn-small"><i class="icon-white icon-plus icon-large"></i></button>
	  	<%= text_field_tag 'playlist[title]', nil, placeholder: 'Enter Playlist Title...' %>
	  <% end %>
	<% end %>

  <ul class="search-results list-unstyled playlist-small">
   <% if @playlist.nil? or @playlist.playlist_entries.nil? %>
    <li class="placeholder">Playlist ist leer...</li>
   <% else %>
    <% @playlist.playlist_entries.each do |entry| %>
      <li class="clearfix" data-song-id="<%= entry.song.sid %>" data-entry-id="<%= entry.id %>">
        <div class="search-thumbnail thumbnail pull-left">
         
          <i class='icon-play-circle icon-large'></i>
        </div>
        <div>
            <p class="pull-right">
             <%= link_to raw("&times;"), playlist_playlist_entry_remove_path(@playlist, entry.id), 
                    :method => :delete, :remote=>true, :class=>"close" %> 
                     
             <%= link_to raw("<i class='icon-plus-sign'></i>"), "playlists/addSong/" + entry.song.sid, :remote=>true, :class=>"btn btn-small add-song" %>          
              <span title="start playing..." class="btn btn-small play-song"><i class='icon-play'></i></span>
            </p>
          <p class="truncate artistname"><%= entry.song.artist %></p>
          <p class="truncate songtitle">
            <%= link_to entry.song.title, song_path(entry.song.sid), :remote => true %>
          </p>
        </div>
      </li>
    <% end %>
   <% end %>
  </ul>
</div>

app/views/playlists/edit.html.erb
<h1>Editing playlist</h1>

<%= render 'form' %>

app/views/playlists/index.html.erb
<div class="row-fluid">
  <h1>Listing playlists <%= link_to raw('New Playlist <i class="icon-plus"></i>'), new_playlist_path, :class => "btn btn-link" %></h1>

  <%= render :partial => "list_with_owner" %>
</div>    

app/views/playlists/new.html.erb
<h1>New playlist</h1>

<%= render 'form' %>

app/views/playlists/show.html.erb
<div class="row">
  <div class="col-md-4">
    <p>
      <b>Tilte:</b>
      <%= @playlist.title %>
    </p>

    <p>
      <b>Description:</b>
      <%= @playlist.description %>
    </p>

    <p>
      <b>User:</b>
      <%= @playlist.creator.name %>
    </p>

    <p>
      <b>Published:</b>
      <%= check_box_tag 'published', '', @playlist.published, :disabled => true %>
    </p>

    <p>
      <b>created at:</b>
      <%= @playlist.created_at %>
    </p>
  </div>
  <div class="col-md-8">
    <%= will_paginate @playlist_entries, renderer: BootstrapPagination::Rails %>
    <table class="table">
      <tr>
        <th>#</th>
        <th>Title</th>
        <th></th>
      </tr>

    <% @playlist_entries.each.with_index do |entry, number| %>
      <tr>
        <td><%= number + 1 + @playlist_entries.offset %></td>
        <td><%= entry.song.artist %> - <%= entry.song.title %></td>
        <td><%= link_to 'Show', song_path(entry.song.sid), :class => "btn btn-link" %>
            <%= link_to 'Remove', playlist_playlist_entry_remove_path(@playlist, entry.id), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-link" %></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>

<%= link_to 'Edit', edit_playlist_path(@playlist), :class => "btn btn-link" %>
<%= link_to 'Play', select_playlist_path(@playlist), :class => "btn btn-link" %>
<%= link_to 'Back', playlists_path, :class => "btn btn-link" %>