config/routes.rb
YoumixrOR::Application.routes.draw do

  root :to => "static_pages#home"

  get "home", to: "static_pages#home"
  get "help", to:  "static_pages#help"
  get "run", to: "static_pages#run"

  get "log_out" => "sessions#destroy", as: :log_out
  get "session", to: "static_pages#index"
  resource :sessions
  
  resources :histories, :only => [:delete, :show]

  resources :users, constraints: {id: /\d+/}, except: [:index] do 
    resources :histories, only: [:index]
    member do
      get 'playlists', to: 'users#playlists', constraints: {id: /\d+/}
    end
  end

  resources :playlists, constraints: {id: /\d+/} do
    member do
      get 'select'
    end

    collection do
      get 'addSong/:sid', to: 'playlist_entries#create', constraints: {sid: /yt:(\w|-)+|sc:\d+|vi:\d+/}
      get 'removeSong/:playlist_entry_id', to: 'playlist_entries#destroy', constraints: {playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id/:next_playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/, next_playlist_entry_id: /\d+/}
      get 'reorder/:playlist_entry_id', 
          to: 'playlist_entries#reorder', constraints: {playlist_entry_id: /\d+/}
    end

    resources :playlist_entries, only: [:destroy, :create], constraints: {id: /\d+/} do
      post 'add', to: :create
      delete 'remove', to: :destroy 
    end
  end
  
  get '/songs/soundcloudTemplate', to: "songs#soundcloudTemplate"

  resources :songs, constraints: {id: /yt:(\w|-)+|sc:\d+|vi:\d+/} do  
    member do 
      get 'play'
    end
    collection do
      get "search"
    end
  end

  resources :vimeo, controller: :vimeo_wrappers, only: [:index]

end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
      	<%= link_to "ymixr Alpha 0.2", root_path, :class=>"navbar-brand" %>
      </div>

      <p class="navbar-text navbar-right">
  	    <%= link_to raw("&copy; Johannes Koch 2013"), "mailto:jkoch.contact@gmail.com?subject=ymixr%20Review", :class => "navbar-link" %>
      </p>
    </div>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">

    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "ymixr Alpha 0.2", root_path, :class=>"navbar-brand" %>

      <div class="player player-xs"> 
        <button class="btn btn-inverse btn-xs btn-play">
          <i class="icon-play icon-white"></i>
        </button>
        <button class="btn btn-inverse btn-xs btn-forward">
          <i class="icon-step-forward icon-white"></i>
        </button>
      </div>
    </div> 

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <%= form_tag(search_songs_path, :id => "search-form",:remote => true, :class => "navbar-form navbar-left search-form-header hidden-xs", :role => "search") do -%>
        <div class="input-group">
          <input name="song_search" type="text" class="form-control">
          <span class="input-group-btn">
            <button class="btn btn-default" type="submit">Go!</button>
          </span>
        </div>
      <% end %>
      <div class="player player-lg navbar-left truncate">
        <button class="btn btn-inverse btn-xs btn-play">
          <i class="icon-play icon-white"></i>
        </button>
        <button class="btn btn-inverse btn-xs btn-forward">
          <i class="icon-step-forward icon-white"></i>
        </button>
        <span class="songtitle"></span>      
        <div id='progressbar'></div>
      </div>
      <ul class="nav navbar-nav navbar-right">
          <li class="player-wrapper">  <!-- .visible bootstrap class?! --> 
          </li>
          <li><%= link_to "Home", home_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if current_user.nil? %>
            <li><%= link_to "Register", new_user_path %></li> 
            <li><%= link_to "Sign in", new_sessions_path %></li>
          <% else %>
            <li class="dropdown">
              <%= link_to raw("Eingeloggt als " + current_user.name + "<span class='caret'></span>"), users_path, :class => "dropdown-toggle", :data => {:toggle => "dropdown"} %>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to "Show Profil", user_path(current_user) %></li>
                  <li><%= link_to "Edit Profil", edit_user_path(current_user) %></li>
                  <li class="divider"></li>
                  <li><%= link_to "Playlists", playlists_user_path(current_user) %></li>
                  <li><%= link_to "History", user_histories_path(current_user) %></li>
                </ul> 
            </li>
            <li><%= link_to "Logout", log_out_path %></li>
          <% end %>
        </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>
</header>

app/views/layouts/_searchform.html.erb
<div class="row panel panel-default">
  <div class="panel-heading"><h3>Filter !!!</h3></div>
  <%= form_tag(search_songs_path, :remote => true, :class => "sidebar-nav panel-body") do -%>

    <div class="form-group search-form-sidebar visible-xs">
      <input type="text" name="song_search" placeholder="Search" class="form-control">
      <button class="btn btn-default btn-lg btn-block" type="submit">Go!</button>
    </div>

    <% params[:source_filter] = (params[:source_filter].nil?) ? "yt" : params[:source_filter] %>
    <%- Youmixr::Plattform.each_pair do |key, value| %>
      <div class="checkbox">
        <label>
          <input name="source_filter" <%=if !params[:source_filter].nil? && params[:source_filter].include?(key) then "checked" end %> value="<%= key %>" type="checkbox"> <%= value %>
        </label>
      </div>
    <% end %>
  <% end -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ymixr - Alpha 0.2 </title>
 <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <!--  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  
        <script src="http://code.jquery.com/ui/1.10.3/jquery-ui.js"></script>
  -->
  <link href="//netdna.bootstrapcdn.com/font-awesome/3.2.1/css/font-awesome.css" rel="stylesheet">

  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  

</head>
<body>
  <%= render "layouts/header" %>
   
  <div class="container-fluid" id="mainframe">

    <%= yield %>

  </div>

  <%= render "layouts/footer" %>
</body>
<script>
      // 2. This code loads the Youtube IFrame Player API code asynchronously.
      var tag = document.createElement('script');
      tag.src = "http://www.youtube.com/player_api";
      var firstScriptTag = document.getElementsByTagName('script')[0];
      firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
</script> 


<script src="https://connect.soundcloud.com/sdk.js"></script>
<script>
  SC.initialize({
    client_id: "4534af5d3c15ffc9c03f4ee826ad5265"
  });

  function gapiOnLoad(){
    gapi.client.setApiKey('AIzaSyCTTUzmudt7NUSeoR03piIcWW1kA7ocUQI');
    gapi.client.load('youtube', 'v3', function() { 
        gapiLoaded = true; 
        ytLoadThumbnails();
    });    
  }

</script>
<script src="https://apis.google.com/js/client.js?onload=gapiOnLoad"></script>
<script src="http://a.vimeocdn.com/js/froogaloop2.min.js"></script>
</html>

app/views/layouts/index.html.erb
<section>
  <div class="hidden-player">
    <div id="ytPlayer"></div>
    <div id="viPlayer"></div>
  </div>
  <% if notice %>
  <div class="alert alert-info alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    <strong>Warning!</strong> <%= notice %>
  </div>
  <% end %>
</section>

<section id="mixr">
  <div class="row-fluid">
    <%= render "playlists/small_list" %>
    <div class="col-md-8 search-result-container">
      <%= render "layouts/searchform" %>
      <div class="row search-results-header">
        <h1>Search Results</h1>
        <p>
        	<button id="show-sc-results" type="button" class="btn btn-default btn-xs pull-right">Soundcloud</button>	
        	<button id="show-vi-results" type="button" class="btn btn-default btn-xs pull-right">Vimeo</button>
        	<button id="show-yt-results" type="button" class="btn btn-default btn-xs pull-right">Youtube</button>	
        </p>
      </div>        
      <div class="row">
        <div class="search-result-loading">
        	<i class="icon-spinner icon-spin icon-large"></i> Loading ...
        </div>
        <ul class="search-result-list search-result-list-yt unstyled connectedSortable"></ul>
        <ul class="search-result-list search-result-list-sc unstyled connectedSortable"></ul>
        <ul class="search-result-list search-result-list-vi unstyled connectedSortable"></ul>
      </div>
    </div>      
  </div>
</section>